---
- name: Update yum
  yum:
    name: '*'
    state: latest
  tags: common

- name: Install yum package
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ yum_install }}"
  notify: Start httpd
  tags: common
