---
- name: Enable to install php7.2
  shell: amazon-linux-extras install php7.2
  tags: php

- name: Install PHP
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ yum_install }}"
  tags: php
